# docker
FROM ruby:3.2.2-alpine3.18
WORKDIR /app

ENV PASSENGER_VERSION="6.0.19" \
    VERBOSE=1 \
    PATH="/opt/passenger/bin:$PATH"


RUN apk add --no-cache --update --repository=https://dl-cdn.alpinelinux.org/alpine/v3.16/main/ libexecinfo-dev

RUN PACKAGES="ca-certificates ruby procps curl pcre libstdc++" && \
    BUILD_PACKAGES="build-base ruby-dev linux-headers curl-dev pcre-dev" && \
    apk add --update $PACKAGES $BUILD_PACKAGES && \
    # download and extract
    mkdir -p /opt && \
    curl -L https://s3.amazonaws.com/phusion-passenger/releases/passenger-$PASSENGER_VERSION.tar.gz | tar -xzf - -C /opt && \
    mv /opt/passenger-$PASSENGER_VERSION /opt/passenger && \
    export EXTRA_PRE_CFLAGS='-O' EXTRA_PRE_CXXFLAGS='-O' EXTRA_LDFLAGS='-lexecinfo' && \
    # compile agent
    passenger-config compile-agent --auto --optimize && \
    passenger-config install-standalone-runtime --auto --url-root=fake && \
    passenger-config build-native-support && \
    # app directory
    mkdir -p /usr/src/app && \
    # Cleanup passenger src directory
    rm -rf /tmp/* && \
    mv /opt/passenger/src/ruby_supportlib /tmp && \
    mv /opt/passenger/src/nodejs_supportlib /tmp && \
    mv /opt/passenger/src/helper-scripts /tmp && \
    rm -rf /opt/passenger/src/* && \
    mv /tmp/* /opt/passenger/src/ && \
    # Cleanup
    passenger-config validate-install --auto && \
    apk del $BUILD_PACKAGES && \
    rm -rf /var/cache/apk/* \
        /tmp/* \
        /opt/passenger/doc

CMD ["passenger", "start"]